# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: equuaam
images:
  - name: nginx # match images with this name
    newTag: 1.16 # override the tag
    newName: nginx-special # override the name
resources:
- deployment.yaml